#!/usr/bin/env python3
"""
prep_writer.py — Prep Document Manager

CRUD operations for interview prep document sets.
Each prep lives in preps/{slug}/ with standardized files.

Usage:
    python3 prep_writer.py --action create --slug google-swe --base-dir ./preps
    python3 prep_writer.py --action list --base-dir ./preps
    python3 prep_writer.py --action update --slug google-swe --base-dir ./preps
    python3 prep_writer.py --action export --slug google-swe --format md --base-dir ./preps
    python3 prep_writer.py --action delete --slug google-swe --base-dir ./preps
    python3 prep_writer.py --help
"""

import argparse
import json
import re
import sys
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional


SLUG_PATTERN = re.compile(r'^[a-zA-Z0-9][a-zA-Z0-9_-]*$')


def validate_slug(slug: str) -> Optional[str]:
    """Validate slug. Returns error message if invalid, None if OK."""
    if not slug or len(slug) > 100:
        return "Slug must be 1-100 characters"
    if not SLUG_PATTERN.match(slug):
        return "Slug must contain only letters, digits, hyphens, and underscores"
    if ".." in slug or "/" in slug or "\\" in slug:
        return "Slug must not contain path separators"
    return None


PREP_FILES = [
    "company_brief.md",
    "questions.md",
    "mock_script.md",
    "prep_plan.md",
    "meta.json",
    "SKILL.md",
]

def create_prep(slug: str, base_dir: Path) -> dict:
    """Create a new prep directory with template files."""
    prep_dir = base_dir / slug
    if prep_dir.exists():
        return {"error": "exists", "message": f"Prep '{slug}' already exists at {prep_dir}"}

    prep_dir.mkdir(parents=True)
    (prep_dir / "knowledge").mkdir()

    # Create meta.json template
    meta = {
        "company": "",
        "role": "",
        "slug": slug,
        "round": "",
        "language": "en",
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
        "version": "v1",
        "research_confidence": "",
        "research_sources": 0,
        "questions_count": 0,
        "mock_completed": False,
        "mock_score": None,
        "real_interview_completed": False,
        "corrections_count": 0,
    }
    (prep_dir / "meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    # Create placeholder files
    for f in PREP_FILES:
        if f != "meta.json":
            (prep_dir / f).write_text(f"# {slug}\n\n> Generated by interview-skill. Fill in content.\n", encoding="utf-8")

    return {"status": "created", "path": str(prep_dir), "files": PREP_FILES}


def list_preps(base_dir: Path) -> dict:
    """List all existing preps with summary info."""
    if not base_dir.exists():
        return {"preps": [], "total": 0}

    preps = []
    for d in sorted(base_dir.iterdir()):
        if d.is_dir() and not d.name.startswith("."):
            meta_path = d / "meta.json"
            info = {"slug": d.name, "path": str(d)}
            if meta_path.exists():
                try:
                    meta = json.loads(meta_path.read_text(encoding="utf-8"))
                    info.update({
                        "company": meta.get("company", ""),
                        "role": meta.get("role", ""),
                        "version": meta.get("version", ""),
                        "research_confidence": meta.get("research_confidence", ""),
                        "updated_at": meta.get("updated_at", ""),
                    })
                except json.JSONDecodeError:
                    pass
            preps.append(info)
    return {"preps": preps, "total": len(preps)}


def export_prep(slug: str, base_dir: Path, fmt: str = "md") -> dict:
    """Export a prep as a single combined file."""
    prep_dir = base_dir / slug
    if not prep_dir.exists():
        return {"error": "not_found", "message": f"Prep '{slug}' not found"}

    parts = []
    for f in ["company_brief.md", "questions.md", "mock_script.md", "prep_plan.md"]:
        fp = prep_dir / f
        if fp.exists():
            content = fp.read_text(encoding="utf-8")
            parts.append(f"---\n\n# {f}\n\n{content}")

    combined = f"# {slug} — Interview Prep Export\n\n" + "\n".join(parts)
    export_path = prep_dir / f"export.{fmt}"
    export_path.write_text(combined, encoding="utf-8")

    return {"status": "exported", "path": str(export_path), "format": fmt}


def delete_prep(slug: str, base_dir: Path) -> dict:
    """Delete a prep (requires confirmation at caller level)."""
    prep_dir = base_dir / slug
    if not prep_dir.exists():
        return {"error": "not_found", "message": f"Prep '{slug}' not found"}
    shutil.rmtree(prep_dir)
    return {"status": "deleted", "slug": slug}

def main():
    parser = argparse.ArgumentParser(description="Manage interview prep documents")
    parser.add_argument("--action", required=True,
                       choices=["create", "list", "update", "export", "delete"],
                       help="Action to perform")
    parser.add_argument("--slug", help="Prep identifier (e.g., google-swe)")
    parser.add_argument("--base-dir", default="./preps", help="Base directory for preps")
    parser.add_argument("--format", default="md", choices=["md", "txt"], help="Export format")
    args = parser.parse_args()

    base = Path(args.base_dir)

    # Validate slug for actions that need it
    if args.action in ("create", "export", "delete") and args.slug:
        slug_err = validate_slug(args.slug)
        if slug_err:
            print(json.dumps({"error": "invalid_slug", "message": slug_err}))
            sys.exit(1)

    if args.action == "create":
        if not args.slug:
            print(json.dumps({"error": "missing_slug", "message": "Provide --slug for create"}))
            sys.exit(1)
        result = create_prep(args.slug, base)
    elif args.action == "list":
        result = list_preps(base)
    elif args.action == "export":
        if not args.slug:
            print(json.dumps({"error": "missing_slug", "message": "Provide --slug for export"}))
            sys.exit(1)
        result = export_prep(args.slug, base, args.format)
    elif args.action == "delete":
        if not args.slug:
            print(json.dumps({"error": "missing_slug", "message": "Provide --slug for delete"}))
            sys.exit(1)
        result = delete_prep(args.slug, base)
    else:
        result = {"error": "unknown_action", "message": f"Unknown action: {args.action}"}

    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()